export const FETCH_ALL_SALES_PENDING = 'FETCH_ALL_SALES_PENDING'
export const FETCH_ALL_SALES_SUCCESS = 'FETCH_ALL_SALES_SUCCESS'
export const FETCH_ALL_SALES_FAILED = 'FETCH_ALL_SALES_FAILED'

export const FETCH_ONE_SALE_PENDING = 'FETCH_ONE_SALE_PENDING'
export const FETCH_ONE_SALE_SUCCESS = 'FETCH_ONE_SALE_SUCCESS'
export const FETCH_ONE_SALE_FAILED = 'FETCH_ONE_SALE_FAILED'

export const REMOVE_SALE_PENDING = 'REMOVE_SALE_PENDING'
export const REMOVE_SALE_SUCCESS = 'REMOVE_SALE_SUCCESS'
export const REMOVE_SALE_FAILED = 'REMOVE_SALE_FAILED'

export const ADD_NEW_SALE_PENDING = 'ADD_NEW_SALE_PENDING'
export const ADD_NEW_SALE_SUCCESS = 'ADD_NEW_SALE_SUCCESS'
export const ADD_NEW_SALE_FAILED = 'ADD_NEW_SALE_FAILED'

export const EDIT_ONE_SALE_PENDING = 'EDIT_ONE_SALE_PENDING'
export const EDIT_ONE_SALE_SUCCESS = 'EDIT_ONE_SALE_SUCCESS'
export const EDIT_ONE_SALE_FAILED = 'EDIT_ONE_SALE_FAILED'